import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import { useQuery } from "@apollo/client";
import { GET_PRODUCTS } from "@/graphql/query";
import { Product as IProduct } from "@/models";
import Link from "next/link";
import dynamic from "next/dynamic";

const Product = dynamic(() => import("../components/Product"));

export default function Home() {
  // Here will show 8 latest products for
  // 'New Arrivals' section.
  const { loading, error, data } = useQuery(GET_PRODUCTS, {
    variables: {
      orderBy: [{ column: "created_at", order: "DESC" }],
      first: 8,
    },
  });

  return (
    <>
      <Head>
        <title>Lavax Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <Layout>
        <div className="flex h-[720px] w-full items-center justify-between bg-gray-100 px-[135px]">
          <div>
            <h1 className="max-w-[423px] text-5xl font-medium">
              Stay Hydrated in Style with Durable and Sustainable Water Bottles
            </h1>

            <Link
              href="/products"
              className="mt-10 inline-block border border-black px-6 py-2"
            >
              Go to products
            </Link>
          </div>

          <div className="flex gap-x-7">
            <div className="relative mt-10 h-[540px] w-[270px]">
              <Image
                src="/metal-water-bottle.png"
                alt="Hero Image 1"
                fill
                className="object-cover"
                priority
              />
            </div>

            <div className="relative h-[540px] w-[270px]">
              <Image
                src="/stainless-steel-water-bottle.png"
                alt="Hero Image 1"
                fill={true}
                className="object-cover"
                priority
              />
            </div>
          </div>
        </div>

        <main className="mx-auto mt-20 max-w-6xl">
          <h2 className="text-center text-4xl font-medium">New Arrivals</h2>

          <div className="mt-9 grid grid-cols-4 gap-x-8">
            {!loading && !error && data.products.data.length
              ? data.products.data.map((product: IProduct) => (
                  <Product
                    key={`new-arrivals-${product.slug}`}
                    slug={product.slug}
                    title={product.title}
                    photoUrl={product.photoUrl!}
                    price={product.price!}
                  />
                ))
              : null}
          </div>

          <div className="flex items-center justify-center py-12">
            <Link
              href="/products"
              className="rounded bg-black px-8 py-3 font-medium text-white"
            >
              See All Products
            </Link>
          </div>
        </main>
      </Layout>
    </>
  );
}
